name: Build and Test Docker Image

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-24.04-arm 

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: go build
        run: |
          go mod tidy
          go build

      - uses: softprops/action-gh-release@v2
        with:
          files: esAlert

